logging:
  level:
    org.springframework.security: INFO

resilience4j.retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
