hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - StripPrefix=0
        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/bills/**
          filters:
            - StripPrefix=0
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposits/**
          filters:
            - StripPrefix=0
        - id: payment-service
          uri: lb://payment-service
          predicates:
              - Path=/payments/**
          filters:
              - StripPrefix=0

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8989
